tfn_dbt:
  outputs:
    dev:
      type: bigquery
      project: tfn-data-warehouse
      dataset: dbt_tests
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
      method: oauth

    prod:
      type: bigquery
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET', 'analytics') }}"
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: batch
      retries: 1
      method: oauth

  target: dev
